### ISSUE TITLE
Making canonical redirect only for GET/HEAD

### ISSUE THREAD

**Issue by ivanvenosdel** [matthiask/django-canonical-domain#1]
## A little history

I have a situation where a webhook was initially configured with a version of my domain that was not the canonical. Though the setting has since been corrected the service already queued the previous version and seems to be retrying until it gets the expected response (not 301). 

## Proposed changed
None of that is a problem with django-canonical-domain. However it does cause me to wonder what the point of redirecting any HTTP method other than GET/HEAD to the canonical domain in the first place, considering search engine crawlers will only ever use GET/HEAD. 

So I would like to propose one of the following changes:
1. Update the [the matching code](https://github.com/matthiask/django-canonical-domain/blob/master/canonical_domain/middleware.py#L29) to require `request.method in ['GET', 'HEAD']`. 
2. The behavior in 1 but make it optional by way of a setting.
3. Refactor the matching logic into a method that can be more easily be overridden by a subclass.

Happy to contribute a PR for this, if helpful, just let me know. Thanks for the useful project!

**Comment by matthiask** [comment]
Thank you for the report. I definitely agree with 1. Please contribute a PR!

**Comment by matthiask** [comment]
Sorry -- just did this myself now, and already rolled a release. 0.3 is available on PyPI!

**Comment by ivanvenosdel** [comment]
Certainly fine with me, I was just getting started anyway. Thanks for the quick PyPI release!
